### ISSUE TITLE
CComplexSplitter

### ISSUE THREAD

**Issue by yg88** [MR-algorithms/YAP#15]
Given a complex array, this processor separate it to real and imaginary parts. If property "CreateReal" is true, then the real part will be feed to out port "Real"; if property "Imaginary" is true, then the imaginary part will be feed to out port "Imaginary".

**Comment by LiDongbao** [comment]
ok, I will do this part!

**Comment by LiDongbao** [comment]
Done this Issue and send Pull request already.
